---
- name: Install nginx latest version
  apt:
    state: latest
    update_cache: yes
    upgrade: yes

- name: Remove default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup nginx service
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service

- name: display
  shell: systemctl status nginx
    