pipeline {
  agent { label 'jenkins' }
  environment {
    WORK_SUB_DIR          = 'vm-based/infra/packer'
  }  
  stages {
    stage('terraform-apply') {
      // agent {
      //   docker {
      //     image 'ksandermann/cloud-toolbox:latest'
      //   }
      // }
      options {
        timeout(time: 10, unit: 'MINUTES')
      }

      steps {
        withCredentials([
          usernamePassword(credentialsId: '	0f288b0d-8d5b-4ecd-9fb3-094e63ee8ca1', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY')
        ]) {
        sh '''
          cd "${WORK_SUB_DIR}"
          terraform init        
          terraform apply -auto-approve -var access_key=${AWS_KEY} -var secret_key=${AWS_SECRET}
        '''
        }
      }
    }

    stage('packaging-image') {
      // agent {
      //   docker {
      //     image 'jeduoliveira/terraform-packer-aws-alpine:latest'
      //   }
      // }     
      options {
        timeout(time: 150, unit: 'MINUTES')
      }
 
      steps {
        withCredentials([
            usernamePassword(credentialsId: '	0f288b0d-8d5b-4ecd-9fb3-094e63ee8ca1', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY')
          ]) {
        sh '''
          cd "${WORK_SUB_DIR}"
          for role_name in app web
          do
            export role_name=$role_name
            packer validate  -var aws_access_key=${AWS_KEY} -var aws_secret_key=${AWS_SECRET} -var-file variables.json packer.json
            packer build  -var aws_access_key=${AWS_KEY} -var aws_secret_key=${AWS_SECRET} -var-file variables.json packer.json
          done
          '''
          }
      }
    }
  }

  // post {
  //   cleanup {
  //     withCredentials([
  //         usernamePassword(credentialsId: '63715168-c881-45f2-a269-873208bf331e', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY'),
  //       ]) {
  //         sh '''
  //           cd "${WORK_SUB_DIR}"
  //           terraform destroy -state="terraform.tfstate" -auto-approve -var access_key=${AWS_KEY} -var secret_key=${AWS_SECRET}
  //           '''
  //         }
  //      }
  // }
}
