pipeline {
  agent none
  environment {
    AWS_ACCESS_KEY_ID     = credentials('PACKER_AWS_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = credentials('PACKER_AWS_SECRET_KEY')
    WORK_SUB_DIR          = 'vm-based/infra/packer'
    JENKINS_USER_ID       = 'user'
    JENKINS_API_TOKEN     = credentials('JENKIN_API_TOKEN')
  }


  
  stages {
    stage('terraform-apply') {
      options {
        timeout(time: 10, unit: 'MINUTES')
      }
      agent {
        docker {
          // image 'jeduoliveira/terraform-packer-aws-alpine:latest'
          image 'codebarber/ansible-packer-terraform:latest'
        }
      }

      steps {
        withCredentials([
          usernamePassword(credentialsId: '63715168-c881-45f2-a269-873208bf331e', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY'),
          string(credentialsId: 'github_personal_token', variable: 'GITHUB_TOKEN'),
        ]) {
        sh '''
          rm -rf node-app-terraform
          git clone https://${GITHUB_TOKEN}@github.com:dangkischnell/immutable-infra.git
          cd immutable-infra
          terraform init
          cd "${WORK_SUB_DIR}"
          terraform init        
          terraform apply -auto-approve -var access_key=${AWS_KEY} -var secret_key=${AWS_SECRET}
        '''
        }
      }
    }

    stage('packaging-image') {
      options {
        timeout(time: 150, unit: 'MINUTES')
      }
      agent {
        docker {
          // image 'ksandermann/cloud-toolbox:latest'
          image 'codebarber/ansible-packer-terraform:latest'
        }
      }   
      steps {
        withCredentials([
            usernamePassword(credentialsId: '63715168-c881-45f2-a269-873208bf331e', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY'),
          ]) {
        sh '''
          cd "${WORK_SUB_DIR}"
          for role_name in app web
          do
            export role_name=$role_name
            packer validate -var aws_access_key=${AWS_KEY} -var aws_secret_key=${AWS_SECRET} -var-file variables.json packer.json
            packer build -var aws_access_key=${AWS_KEY} -var aws_secret_key=${AWS_SECRET} -var-file variables.json packer.json
          done
          '''
          }
      }
    }
  }

  // post {
  //   cleanup {
  //     withCredentials([
  //         usernamePassword(credentialsId: '63715168-c881-45f2-a269-873208bf331e', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY')
  //       ]) {
  //         sh '''
  //           cd "${WORK_SUB_DIR}"
  //           terraform destroy -state="terraform.tfstate" -auto-approve -var access_key=${AWS_KEY} -var secret_key=${AWS_SECRET}
  //           '''
  //         }
  //      }
  // }
}
